from typing import Any, Dict


def is_bot_event(payload: Dict[str, Any]) -> bool:
    """
    Returns True if the event was generated by a bot account or automated app.
    Prevents self-loop execution when the agent posts issue comments on GitHub.
    """
    # 1. Check sender
    sender = payload.get("sender", {})
    sender_type = sender.get("type", "").lower()
    sender_login = sender.get("login", "").lower()

    if sender_type == "bot":
        return True

    if sender_login.endswith("[bot]") or "bot" in sender_login:
        return True

    # 2. Check comment author if applicable
    comment = payload.get("comment", {})
    if comment:
        user = comment.get("user", {})
        if user.get("type", "").lower() == "bot":
            return True
        if user.get("login", "").lower().endswith("[bot]"):
            return True

    return False
