from abc import ABC, abstractmethod
from typing import Any, Dict, Optional, Tuple
from gateway.app.schemas.events import HumanInteractionEvent


class BaseSurfaceAdapter(ABC):
    """
    Abstract Base Class for multi-surface webhook adapters (GitHub, Slack, Discord, Gemini Enterprise).
    """

    @abstractmethod
    def verify_signature(self, raw_body: bytes, headers: Dict[str, str]) -> bool:
        """Verifies surface-specific cryptographic signature (HMAC, RSA, Ed25519)."""
        pass

    @abstractmethod
    def is_bot_event(self, payload: Dict[str, Any]) -> bool:
        """Determines whether the event was generated by a bot account."""
        pass

    @abstractmethod
    def parse_and_normalize(self, payload: Dict[str, Any], headers: Dict[str, str]) -> HumanInteractionEvent:
        """Parses raw surface payload into canonical HumanInteractionEvent model."""
        pass
